"""Add mental health screening features

Revision ID: 1e94820fb65e
Revises: 1875158eefe9
Create Date: 2025-12-29 12:54:29.708387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e94820fb65e'
down_revision = '1875158eefe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbolic_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('linked_to_training_module', sa.String(length=255), nullable=True),
    sa.Column('linked_to_event_type', sa.String(length=100), nullable=True),
    sa.Column('total_quantity', sa.Integer(), nullable=True),
    sa.Column('distributed_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('blog_posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('featured_image', sa.String(length=500), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('post_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('daily_affirmations',
    sa.Column('affirmation_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('times_sent', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('affirmation_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('mental_health_assessments',
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('assessment_type', sa.String(length=50), nullable=False),
    sa.Column('assessment_date', sa.DateTime(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.String(length=50), nullable=True),
    sa.Column('is_baseline', sa.Boolean(), nullable=True),
    sa.Column('assessment_period', sa.String(length=50), nullable=True),
    sa.Column('item_scores', sa.JSON(), nullable=True),
    sa.Column('risk_flagged', sa.Boolean(), nullable=True),
    sa.Column('referral_recommended', sa.Boolean(), nullable=True),
    sa.Column('referral_made', sa.Boolean(), nullable=True),
    sa.Column('administered_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['administered_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('affirmation_deliveries',
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('affirmation_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=False),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('viewed', sa.Boolean(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('liked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['affirmation_id'], ['daily_affirmations.affirmation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('event_participations',
    sa.Column('participation_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('registration_status', sa.String(length=50), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('attendance_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('attendance_confirmed_by', sa.Integer(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('feedback_comments', sa.Text(), nullable=True),
    sa.Column('certificate_issued', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_confirmed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participation_id')
    )
    
    # Rename training_records primary key column BEFORE creating foreign keys to it
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.alter_column('traning_record_id', new_column_name='training_id')
        batch_op.add_column(sa.Column('is_mhrt', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mhrt_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('skills_acquired', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('practical_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('symbolic_item_received', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('symbolic_item_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('symbolic_item_date', sa.Date(), nullable=True))
    
    # Now create item_distributions with foreign key to training_records.training_id
    op.create_table('item_distributions',
    sa.Column('distribution_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('distributed_at', sa.DateTime(), nullable=False),
    sa.Column('distributed_by', sa.Integer(), nullable=True),
    sa.Column('distribution_reason', sa.String(length=255), nullable=True),
    sa.Column('training_record_id', sa.Integer(), nullable=True),
    sa.Column('event_participation_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distributed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_participation_id'], ['event_participations.participation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['symbolic_items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_record_id'], ['training_records.training_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('distribution_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop item_distributions first (has foreign key to training_records)
    op.drop_table('item_distributions')
    op.drop_table('event_participations')
    op.drop_table('affirmation_deliveries')
    op.drop_table('mental_health_assessments')
    op.drop_table('events')
    op.drop_table('daily_affirmations')
    op.drop_table('blog_posts')
    op.drop_table('symbolic_items')
    
    # Then rename training_id back to traning_record_id
    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_column('symbolic_item_date')
        batch_op.drop_column('symbolic_item_type')
        batch_op.drop_column('symbolic_item_received')
        batch_op.drop_column('practical_hours')
        batch_op.drop_column('skills_acquired')
        batch_op.drop_column('mhrt_level')
        batch_op.drop_column('is_mhrt')
        batch_op.alter_column('training_id', new_column_name='traning_record_id')
    # ### end Alembic commands ###
