"""Initial migration with all models

Revision ID: 519eca3cfb20
Revises: 
Create Date: 2025-12-18 14:51:42.428951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519eca3cfb20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('county_sub_county', sa.String(length=100), nullable=True),
    sa.Column('assigned_champion_code', sa.String(length=20), nullable=False),
    sa.Column('date_of_application', sa.Date(), nullable=True),
    sa.Column('recruitment_source', sa.String(length=100), nullable=True),
    sa.Column('assigned_cohort', sa.String(length=100), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('consent_document_link', sa.String(length=500), nullable=True),
    sa.Column('legal_guardian_name', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('institution_consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('institution_consent_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('champion_id'),
    sa.UniqueConstraint('assigned_champion_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('supervised_champion_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('access_audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('refferal_pathways',
    sa.Column('refferal_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('date_initiated', sa.Date(), nullable=False),
    sa.Column('youth_referred_number', sa.Integer(), nullable=True),
    sa.Column('referral_reasons', sa.Text(), nullable=True),
    sa.Column('referral_destinations', sa.String(length=255), nullable=True),
    sa.Column('referal_outcomes', sa.String(length=50), nullable=True),
    sa.Column('flag_to_referral_days', sa.Integer(), nullable=True),
    sa.Column('feedback_from_service_provider', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('refferal_id')
    )
    op.create_table('training_records',
    sa.Column('traning_record_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('training_module', sa.String(length=255), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=True),
    sa.Column('certification_status', sa.String(length=50), nullable=True),
    sa.Column('next_refresher_due_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('traning_record_id'),
    sa.UniqueConstraint('champion_id', 'training_module', name='_champion_module_uc')
    )
    op.create_table('youth_supports',
    sa.Column('support_id', sa.Integer(), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('reporting_period', sa.Date(), nullable=False),
    sa.Column('weekly_check_in_completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('monthly_mini_screenings_delivered', sa.Integer(), nullable=True),
    sa.Column('referrals_initiated', sa.Integer(), nullable=True),
    sa.Column('flag_timestamp', sa.DateTime(), nullable=True),
    sa.Column('documentation_quality_score', sa.String(length=50), nullable=True),
    sa.Column('self_reported_wellbeing_check', sa.Integer(), nullable=True),
    sa.Column('supervisor_notes', sa.Text(), nullable=True),
    sa.Column('safeguarding_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.champion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('support_id'),
    sa.UniqueConstraint('champion_id', 'reporting_period', name='_champion_period_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('youth_supports')
    op.drop_table('training_records')
    op.drop_table('refferal_pathways')
    op.drop_table('access_audit_logs')
    op.drop_table('users')
    op.drop_table('champions')
    # ### end Alembic commands ###
