"""add_motion_field_to_events

Revision ID: 709cd9ae632d
Revises: 7893d12e324d
Create Date: 2026-01-05 15:22:34.777996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709cd9ae632d'
down_revision = '7893d12e324d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('motion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'motion')
    # ### end Alembic commands ###
