"""Add seed funding applications model

Revision ID: 7893d12e324d
Revises: 061b1e566d1e
Create Date: 2026-01-03 22:18:46.735060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7893d12e324d'
down_revision = '061b1e566d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_funding_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('applicant_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('student_id_number', sa.String(length=100), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('project_category', sa.String(length=100), nullable=True),
    sa.Column('target_beneficiaries', sa.String(length=255), nullable=True),
    sa.Column('expected_impact', sa.Text(), nullable=True),
    sa.Column('total_budget_requested', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('budget_breakdown', sa.JSON(), nullable=True),
    sa.Column('other_funding_sources', sa.Text(), nullable=True),
    sa.Column('project_start_date', sa.Date(), nullable=True),
    sa.Column('project_end_date', sa.Date(), nullable=True),
    sa.Column('implementation_timeline', sa.Text(), nullable=True),
    sa.Column('proposal_document_url', sa.String(length=500), nullable=True),
    sa.Column('budget_document_url', sa.String(length=500), nullable=True),
    sa.Column('team_members', sa.JSON(), nullable=True),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('approved_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approval_conditions', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('disbursement_date', sa.Date(), nullable=True),
    sa.Column('disbursement_method', sa.String(length=100), nullable=True),
    sa.Column('disbursement_reference', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seed_funding_applications')
    # ### end Alembic commands ###
