"""add event submission tracking columns

Revision ID: add_event_submission_tracking
Revises: zz_add_user_frequent_pages
Create Date: 2026-02-12 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_event_submission_tracking'
down_revision = 'zz_add_user_frequent_pages'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns conditionally to avoid conflicts with auto-migration
    
    # Add submission_status column
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'submission_status'
            ) THEN
                ALTER TABLE events ADD COLUMN submission_status VARCHAR(50);
            END IF;
        END $$;
    """)
    
    # Add submitted_by column
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'submitted_by'
            ) THEN
                ALTER TABLE events ADD COLUMN submitted_by INTEGER;
            END IF;
        END $$;
    """)
    
    # Add reviewed_by column
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'reviewed_by'
            ) THEN
                ALTER TABLE events ADD COLUMN reviewed_by INTEGER;
            END IF;
        END $$;
    """)
    
    # Add reviewed_at column
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'reviewed_at'
            ) THEN
                ALTER TABLE events ADD COLUMN reviewed_at TIMESTAMP;
            END IF;
        END $$;
    """)
    
    # Add rejection_reason column
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'rejection_reason'
            ) THEN
                ALTER TABLE events ADD COLUMN rejection_reason TEXT;
            END IF;
        END $$;
    """)
    
    # Add foreign key constraints conditionally
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'events' AND constraint_name = 'fk_events_submitted_by'
            ) THEN
                ALTER TABLE events ADD CONSTRAINT fk_events_submitted_by
                FOREIGN KEY (submitted_by) REFERENCES users(user_id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'events' AND constraint_name = 'fk_events_reviewed_by'
            ) THEN
                ALTER TABLE events ADD CONSTRAINT fk_events_reviewed_by
                FOREIGN KEY (reviewed_by) REFERENCES users(user_id) ON DELETE SET NULL;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop constraints conditionally
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'events' AND constraint_name = 'fk_events_reviewed_by'
            ) THEN
                ALTER TABLE events DROP CONSTRAINT fk_events_reviewed_by;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE table_name = 'events' AND constraint_name = 'fk_events_submitted_by'
            ) THEN
                ALTER TABLE events DROP CONSTRAINT fk_events_submitted_by;
            END IF;
        END $$;
    """)
    
    # Drop columns conditionally
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'rejection_reason'
            ) THEN
                ALTER TABLE events DROP COLUMN rejection_reason;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'reviewed_at'
            ) THEN
                ALTER TABLE events DROP COLUMN reviewed_at;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'reviewed_by'
            ) THEN
                ALTER TABLE events DROP COLUMN reviewed_by;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'submitted_by'
            ) THEN
                ALTER TABLE events DROP COLUMN submitted_by;
            END IF;
        END $$;
    """)
    
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns 
                WHERE table_name = 'events' AND column_name = 'submission_status'
            ) THEN
                ALTER TABLE events DROP COLUMN submission_status;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###
