"""add event submission tracking columns

Revision ID: add_event_submission_tracking
Revises: zz_add_user_frequent_pages
Create Date: 2026-02-12 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_event_submission_tracking'
down_revision = 'zz_add_user_frequent_pages'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('submission_status', sa.String(50), nullable=True))
    op.add_column('events', sa.Column('submitted_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('rejection_reason', sa.Text(), nullable=True))
    
    # Add foreign key constraints
    op.create_foreign_key('fk_events_submitted_by', 'events', 'users',
                          ['submitted_by'], ['user_id'], ondelete='SET NULL')
    op.create_foreign_key('fk_events_reviewed_by', 'events', 'users',
                          ['reviewed_by'], ['user_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_events_reviewed_by', 'events', type_='foreignkey')
    op.drop_constraint('fk_events_submitted_by', 'events', type_='foreignkey')
    op.drop_column('events', 'rejection_reason')
    op.drop_column('events', 'reviewed_at')
    op.drop_column('events', 'reviewed_by')
    op.drop_column('events', 'submitted_by')
    op.drop_column('events', 'submission_status')
    # ### end Alembic commands ###
