"""Add comprehensive champion data fields: emergency contacts, education, status tracking, performance metrics

Revision ID: ca78f27269e6
Revises: 519eca3cfb20
Create Date: 2025-12-18 17:06:48.655975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca78f27269e6'
down_revision = '519eca3cfb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alternative_phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_education_level', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('education_institution_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('course_field_of_study', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('year_of_study', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('workplace_organization', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('application_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('screening_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('champion_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trainer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('training_location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('certificate_number', sa.String(length=100), nullable=True))

    with op.batch_alter_table('youth_supports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_youth_group_cluster', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('number_of_youth_under_support', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_in_frequency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('follow_up_actions_completed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('engagement_style', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('attendance_monthly_forums_percent', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('participation_in_umv_events', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('youth_feedback_score', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('peer_champion_rating', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('outstanding_contributions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flags_and_concerns_logged', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('safeguarding_training_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('availability_for_duty', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reported_incidents', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('referral_escalation_made', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('follow_up_status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youth_supports', schema=None) as batch_op:
        batch_op.drop_column('follow_up_status')
        batch_op.drop_column('referral_escalation_made')
        batch_op.drop_column('reported_incidents')
        batch_op.drop_column('availability_for_duty')
        batch_op.drop_column('safeguarding_training_completed')
        batch_op.drop_column('flags_and_concerns_logged')
        batch_op.drop_column('outstanding_contributions')
        batch_op.drop_column('peer_champion_rating')
        batch_op.drop_column('youth_feedback_score')
        batch_op.drop_column('participation_in_umv_events')
        batch_op.drop_column('attendance_monthly_forums_percent')
        batch_op.drop_column('engagement_style')
        batch_op.drop_column('follow_up_actions_completed')
        batch_op.drop_column('check_in_frequency')
        batch_op.drop_column('number_of_youth_under_support')
        batch_op.drop_column('assigned_youth_group_cluster')

    with op.batch_alter_table('training_records', schema=None) as batch_op:
        batch_op.drop_column('certificate_number')
        batch_op.drop_column('training_location')
        batch_op.drop_column('trainer_name')

    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.drop_column('champion_status')
        batch_op.drop_column('screening_status')
        batch_op.drop_column('application_status')
        batch_op.drop_column('workplace_organization')
        batch_op.drop_column('year_of_study')
        batch_op.drop_column('course_field_of_study')
        batch_op.drop_column('education_institution_name')
        batch_op.drop_column('current_education_level')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('alternative_phone_number')

    # ### end Alembic commands ###
