"""add published fields to events

Revision ID: f6c0cddf2071
Revises: d42c4ad8c236
Create Date: 2026-02-12 22:05:38.616616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f6c0cddf2071'
down_revision = 'd42c4ad8c236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('partnership_inquiries',
    sa.Column('inquiry_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('partnership_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_table('volunteer_submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('interest', sa.String(length=100), nullable=False),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('event_interests',
    sa.Column('interest_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('interest_id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_champions_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_champions_supervisor', type_='foreignkey')
        batch_op.create_foreign_key('fk_champions_user_id', 'users', ['user_id'], ['user_id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key(None, 'users', ['supervisor_id'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('institutional_toolkit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('media_gallery', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.alter_column('revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index('ix_refresh_tokens_token_hash')
        batch_op.create_unique_constraint(None, ['token_hash'])

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['user_id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['invite_token'])
        batch_op.drop_constraint('fk_users_champion_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_champion_id', 'champions', ['champion_id'], ['champion_id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_champion_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_users_champion_id', 'champions', ['champion_id'], ['champion_id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('ix_refresh_tokens_token_hash', ['token_hash'], unique=True)
        batch_op.alter_column('revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('media_gallery', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('institutional_toolkit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('published')

    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_champions_user_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_champions_supervisor', 'users', ['supervisor_id'], ['user_id'])
        batch_op.create_foreign_key('fk_champions_user_id', 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.drop_table('event_interests')
    op.drop_table('volunteer_submissions')
    op.drop_table('partnership_inquiries')
    op.drop_table('host_submissions')
    # ### end Alembic commands ###
